todolist/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_pyfile('../config.py')

from todolist.database import db, User, refill_db
from todolist.views import home

db.init_app(app)

app.secret_key = 'vhd89kb5upC6J3nPOtf1LVtE' #Random key

from .auth import auth
app.register_blueprint(auth)
from .tasks import tasks
app.register_blueprint(tasks)
from .admin import admin
app.register_blueprint(admin)
from .logs import logs
app.register_blueprint(logs)


#check if db's created inside
with app.app_context():
    refill_db()

todolist/admin/__init__.py
from flask import Blueprint, flash, redirect, url_for
from ..auth import login_manager, login_required, current_user

admin = Blueprint('admin', __name__)

@admin.before_request
@login_required
def admin_access_check():
    if not current_user.is_authenticated:
        return login_manager.unauthorized()
    if not current_user.has_role('Admin'):
        flash('You have no access to this page')
        return redirect(url_for('home'))

from . import adm_views

todolist/database/__init__.py
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()

from .dbscript import ccltypes, dblogtypes 
cycletypes = ccltypes()
logtypes = dblogtypes()

from .dbmodel import *

logtypes.AddType(0,'None',TaskLog)
logtypes.AddType(1,'Float',TaskLogFloat)

from .refill import refill_db

todolist/logs/__init__.py
from flask import Blueprint, flash, redirect, url_for
from ..auth import login_manager, login_required, current_user
from .. import app
from datetime import date
from flask.json import JSONEncoder

logs = Blueprint('logs', __name__)

@logs.before_request
@login_required
def admin_access_check():
    if not current_user.is_authenticated:
        return login_manager.unauthorized()
    if not current_user.has_roles(('Supervisor','Admin', 'User')):
        flash('You have no access to this page')
        return redirect(url_for('home'))

#Views
from .logs_views import *

class CustomJSONEncoder(JSONEncoder):
    def default(self, obj):
        try:
            if isinstance(obj, date):
                return obj.isoformat(' ')
            iterable = iter(obj)
        except TypeError:
            pass
        else:
            return list(iterable)
        return JSONEncoder.default(self, obj)

app.json_encoder = CustomJSONEncoder

todolist/tasks/__init__.py
from flask import Blueprint, flash, redirect, url_for
from ..auth import login_manager, login_required, current_user
from werkzeug import SharedDataMiddleware
from .. import app

tasks = Blueprint('tasks', __name__)
app.add_url_rule('/images/<filename>', 'image_files',
                 build_only=True)
app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {
    '/images':  app.config['IMAGE_FOLDER']
})

@tasks.before_request
@login_required
def admin_access_check():
    if not current_user.is_authenticated:
        return login_manager.unauthorized()
#    if not current_user.has_roles('User'):
#        flash('You have no access to this page')
#        return redirect(url_for('home'))

#Views
from .task_views import *
from .task_admviews import *

todolist/views.py
from flask import request, render_template, flash, redirect
from .auth import current_user, login_required
from todolist import app


@app.route('/')
@app.route('/home')
@login_required
def home():
    return render_template('home.html')

todolist/templates/_formhelpers.html
{% macro render_field(fld) %}
<div class="form-group">
		{{ fld.label(class_="control-label col-sm-2") }}
		<div class="col-sm-10">{{ fld(class_="form-control")|safe }}
		{% if fld.smalltext %}<small class="form-text text-muted">fld.smalltext</small>{% endif %}
		{% if fld.errors %}{% for error in fld.errors %}
		<div class="alert alert-danger alert-dismissable" role='alert'>
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		{{ error }}
		</div>
		{% endfor %}{% endif %}		</div>
	</div>
{% endmacro %}

{% macro render_id_active(form) %}
	<div class="form-group">
		<label class="control-label col-sm-2">{{form.formname}} ID</label>
		<div class="col-sm-2"><input class="form-control" type="text" value="{% if form.id>=0 %}{{form.id}}{% else %}NEW {{form.formname}}{% endif %}" readonly>
		</div>
		<div class="col-sm-4 checkbox"><label>{{ form.active }} {{ form.active.label.text }}</label></div>
	</div>
{% endmacro %}

{% macro render_id(form) %}
<div class="form-group">
	<label class="control-label col-sm-2" >{{form.formname}} ID:</label>
	<div class="col-sm-10"><label class="control-label">{% if form.id>=0 %}{{form.id}}{% else %}NEW {{form.formname}}{% endif %}</label></div>
</div>
{% endmacro %}

{% macro render_btn(key,text,type='primary')%}
<li role="presentation"><button type="submit" name="submit" value="{{key}}" class="btn btn-{{type}}">{{text}}</a></li>
{% endmacro %}

{% macro render_btns(form)%}
<ul class="nav nav-pills nav-fill">{% for btn in form.buttons() %}
{{render_btn(*btn)}}{% endfor %}
</ul>
{% endmacro %}

{% macro render_form(form,panel='default')%} {# Require form.id, form.formname, form.buttons, form.idfield, form.fieldslst #}
<div class="panel panel-{{panel}}">
<div class="panel-heading">{% if form.id>=0 %}Edit {{form.formname}} {% else %}NEW {{form.formname}}{% endif %}</div>
<div class="panel-body">
{% if form.idfield -%}
	{% if form.idfield == 'id-active' -%}
		{{ render_id_active(form) }}
	{%- elif form.idfield == 'id' -%} 
		{{ render_id(form) }}
	{%- endif %}
{%- endif %}
{% for field in form.fieldslst() %}{{render_field(field)}}{% endfor %}
{{ form.hidden_tag() }}
</div>  
<div class="panel-footer">
{{render_btns(form)}}
</div>
</div>
{% endmacro %}

todolist/templates/_nav.html
<ul class="nav navbar-nav">
	{% if current_user.is_authenticated %}
		<li {% if page=='tasks' -%}class="active"{% endif -%}><a href="{{ url_for('tasks.home') }}">Tasks</a></li>
	{%- endif %}
	{% if current_user.is_authenticated and current_user.has_roles(('Admin','Supervisor')) %}
		<li {% if page=='logs' -%}class="active"{% endif -%}><a href="{{ url_for('logs.home')  }}">Logs</a></li>
		<li  class="dropdown {% if page=='Admin' -%}active{% endif -%}">
			<a id='Drop_Admin' class="dropdown-toggle" data-toggle="dropdown" href="#">Admin<span class="caret"></span></a>
			<ul class ="dropdown-menu" role="menu" aria-labelledby="Drop_Admin">
				<li><a href="{{ url_for('tasks.admin') }}">Tasks</a></li>
				{% if current_user.is_authenticated and current_user.has_role('Admin') %}
				<li><a href="{{ url_for('admin.home') }}">Users</a></li>
				<li><a href="{{ url_for('tasks.userequipment') }}">Users ⇄ Tasks</a></li>
				<li><a href="{{ url_for('admin.facilities') }}">Facilities</a></li>			
				{% endif %}
			</ul>
		</li>{% endif %}
	<!--<li><a href="#">About</a></li>-->
</ul>

todolist/templates/_usermenu.html
<div class="navbar-text btn-group pull-right">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
		<i class="glyphicon glyphicon-user"></i>
		{% if current_user.is_authenticated %}
			{% if current_user.nickname -%}
			{{ current_user.nickname }}
			{% else -%}
			{{ current_user.username }}
			{%- endif %}{% else %}
			{% endif %}<span class="caret"></span></a>
	<ul class="dropdown-menu" role="menu">
		{% if current_user.is_authenticated %}
			<li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
		{% else %}
			<li><a href="{{ url_for('auth.login') }}">Log in</a></li>
		{% endif %}
	</ul>
</div>

todolist/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SRO Task Lists</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/datatables.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    {% block style %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('home') }}">
            To<span class="glyphicon glyphicon glyphicon-ok" aria-hidden="true"></span>Do
          </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-navbar-collapse">
		{% if current_user.is_authenticated %}
		{% block navigation %}
			{% include '_nav.html' %}
		{% endblock %}{% endif %}
		{% include '_usermenu.html' %}
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
    <br/>
    <div>
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{category}} alert-dismissable" role='alert'>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ message }}
        </div>
      {% endfor %}
    </div>
    {% block container %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

todolist/templates/home.html
{% extends 'base.html' %}

{% block container %}
  <h1>Welcome to ToDo Lists</h1>
    <h3>Hey {{ current_user.name }}!!</h3>
    <a href="{{ url_for('auth.logout') }}">Click here to logout</a>

	
{% endblock %}

todolist/templates/login.html
{% extends 'home.html' %}
 
{% block container %}
<p><h3>Please login using your txstate netid and password.</h3></p>
  <div class="top-pad">
    <form
        method="POST"
        action="{{ url_for('auth.login') }}"
        role="form">
      {{ form.csrf_token }}
      <div class="form-group">{{ form.username.label }}: {{ form.username() }}</div>
      <div class="form-group">{{ form.password.label }}: {{ form.password() }}</div>
      <div class="form-group">{{ form.remember.label }}: {{ form.remember() }}</div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
{% endblock %}

todolist/templates/logs/logs_plot.html
{% extends 'base.html' %}

{% block container %}
  <h1>Logs</h1>
  <ul class="nav nav-tabs">
    <li role="presentation" {% if name=='donetbl' %}class='active'{%endif%}>
        <a class="nav-link" href="{{ url_for('logs.done_tbl') }}">Done Table</a></li>
    <li role="presentation" {% if name=='floattbl' %}class='active'{%endif%}>
        <a class="nav-link" href="{{ url_for('logs.float_tbl') }}">Float Log Table</a></li>
    <li role="presentation"{% if name=='floatplot' %}class='active'{%endif%}>
        <a class="nav-link" href="{{ url_for('logs.float_plot') }}">Float Log Plot</a></li>
  </ul>

<br>
<div id="svgdiv" style="display:none" width="100%"></div>
<br>
<button type="button" class="btn btn-info" id='DrawBtn'>Replot</button>
<hr>
<div class="table-responsive">
{{ FloatLogsTbl }}
</div>
<hr>


{% endblock %}

{% block style -%}
<style>
.grid line {
  stroke: lightgrey;
  stroke-opacity: 0.7;
}

.grid path {
  stroke-width: 0;
}
</style>
{%- endblock %}


{% block scripts %}
<script src="{{ url_for('static', filename='js/d3.js') }}"></script>
<script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
<script>
function svgplot(data)
{
  var parseTime = d3.timeParse("%Y-%m-%d %H:%M:%S.%f");

  var Xlbl='Dates',Ylbl='Logged Value';
  $("#svgdiv").html("");
  $("#svgdiv").height(500);
  var margin = {top: 10, right: 60, bottom: 80, left: 60};

  var color = d3.schemeCategory10;

  var imgwidth = $("#svgdiv").width();
	var imgheight = $("#svgdiv").height();
	var width = imgwidth - margin.left - margin.right;
	var height = imgheight - margin.top - margin.bottom;

  var svg = d3.select("#svgdiv").append("svg:svg").attr("height" , '100%').attr("width", '100%');

  var AxisX = d3.scaleTime().range([0,width]);
  var AxisY = d3.scaleLinear().range([height,0]);
 //.tickFormat(d3.timeFormat("%Y-%m-%d"))
  var plt=svg.attr('class', 'chart').append('g').attr('transform', 'translate(' + margin.left + ',' + margin.top + ')')

  var xmin=d3.min(data.map(function(d){return parseTime(d.minx)}));
  var xmax=d3.max(data.map(function(d){return parseTime(d.maxx)}));
  var ymin=d3.min(data.map(function(d){return d.miny}));
  var ymax=d3.max(data.map(function(d){return d.maxy}));
  var yminmax=0.05*(ymax-ymin);
  AxisX.domain([xmin,xmax]);
  AxisY.domain([ymin-yminmax,ymax+yminmax]);

  // gridlines in x axis function
  function make_x_gridlines() {  return d3.axisBottom(AxisX).ticks(10) };

  // gridlines in y axis function
  function make_y_gridlines() {	 return d3.axisLeft(AxisY).ticks(5) };

  // add the X gridlines
  plt.append("g").attr("class", "grid")
      .attr("transform", "translate(0," + height + ")")
      .call( make_x_gridlines().tickSize(-height).tickFormat("") );

  // add the Y gridlines
  plt.append("g").attr("class", "grid")
        .call( make_y_gridlines().tickSize(-width).tickFormat("") );

  function PointX(d) { return AxisX(parseTime(d[0])); };
  function PointY(d) { return AxisY(d[1]); };
  var Line = d3.line().x(PointX).y(PointY);

  var lgnd = [];

  data.forEach(function(tskplot,index){
    plt.append("path").attr("class", "line").attr('d',Line(tskplot.data))
    .attr('stroke', color[index]).attr('stroke-width', 2).attr('fill', 'none');
    plt.selectAll("dot").data(tskplot.data).enter().append("circle")
    .attr('stroke', color[index]).attr("fill", color[index])
    .attr("cx", PointX).attr("cy",PointY).attr("r", 3);
    lgnd.push({text:tskplot.name,color:color[index]});
  });




  //Add Legend
  var legend = plt.selectAll(".legend")
      .data(lgnd).enter().append("g").attr("class", "legend")
      .attr("transform", function(d, i) { return "translate(0," + i * 20 + ")"; });
  legend.append("rect").attr("x", width - 18)
      .attr("width", 18).attr("height", 18).style("fill", function(d) { return d.color; });
  legend.append("text").attr("x", width - 24).attr("y", 9).attr("dy", ".35em")
      .style("text-anchor", "end").text(function(d) { return d.text; });

  plt.append("g").attr("class", "axisX").attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(AxisX).tickFormat(d3.timeFormat("%Y-%m-%d")))
    .selectAll("text")
            .style("text-anchor", "end")
            .attr("dx", "-.8em")
            .attr("dy", ".15em")
            .attr("transform", "rotate(-40)");

  plt.append("g").attr("class", "axisY").call(d3.axisLeft(AxisY));

  plt.append('text').attr('class','xlabel').attr("x", width/2).attr("y",height + margin.bottom).attr("dy", "-0.4em")
		.style("text-anchor", "middle").text(Xlbl);
  plt.append("text").attr("transform", "rotate(-90)").attr('class','ylabell').attr("y", 0 - margin.left).attr("x",0 - (height / 2)).attr("dy", "1.2em")
  		.style("text-anchor", "middle").text(Ylbl);
};

$(document).ready(function() {
    var table = $('#LogTable').DataTable({
      "lengthMenu": [ 25, 250, 1000 ],
      columnDefs: [ {
            orderable: false,
            className: 'select-checkbox',
            targets: 0
        } ],
      select: {
            style:    'os',
            selector: 'td:first-child'
        }
	});

  $('#DrawBtn').click( function () {
      var dataArr = [];
      var rowData = table.rows( { selected: true } ).data();
      $.each($(rowData),function(){
       	dataArr.push(this["1"]);
       });

    	var url="{{url_for('logs.api')}}";
    	$.ajax({
    			url:url,
    			type:'GET',
          data: {"tasks": JSON.stringify(dataArr) },
          contentType: "application/json",
          dataType: "json",
    			success: function(data) {
            $("#svgdiv").show();
    				svgplot(data);
    			},
    			error: function(xmlhttprequest, textstatus, message) {
    					alert("An error has occurred making the request:\n" + message);
    			}
    	});

  } );


});//DocumentReady
</script>
{% endblock %}

todolist/templates/logs/logs_tbl.html
{% extends 'base.html' %}

{% block container %}
  <h1>Logs</h1>
  <ul class="nav nav-tabs">
    <li role="presentation" {% if name=='donetbl' %}class='active'{%endif%}>
        <a class="nav-link" href="{{ url_for('logs.done_tbl') }}">Done Table</a></li>
    <li role="presentation" {% if name=='floattbl' %}class='active'{%endif%}>
        <a class="nav-link" href="{{ url_for('logs.float_tbl') }}">Float Log Table</a></li>
    <li role="presentation"{% if name=='floatplot' %}class='active'{%endif%}>
        <a class="nav-link" href="{{ url_for('logs.float_plot') }}">Float Log Plot</a></li>
  </ul>

<hr>
<div class="table-responsive">
{{ LogTbl }}
</div>
<hr>


{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/d3.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
<script>
$(document).ready(function() {
    $('#LogTable').DataTable({
      order: [[ 0, "desc" ]],
      "lengthMenu": [ 25, 250, 1000 ]
	});
});//DocumentReady
</script>
{% endblock %}

todolist/templates/tasks/task_ajax.html
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title" id="TaskEditLabel"><a href="#details" data-toggle="collapse">{{view['title']}}</a></h4>
	<div id="details" class="collapse">
	<table class='table table-sm table-hover'>
	{% for key,val in view['details'] %}
	<tr><th><strong>{{key}}:</strong></th><td width='10px'>&nbsp;</td><td>{{ val }}</td></tr>	
	{% endfor %}
	</table>
	</div>
</div>
<div class="modal-body">
<div class="myMarkdown">
{{view['content']}}
</div>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

todolist/templates/tasks/task_ajax_log.html
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title" id="TaskEditLabel">{{view['title']}}</h4>
</div>
<div class="modal-body">
<form method="post" class="form-horizontal" id="LogForm">
<div class="form-group">
{{ form.value.label(class_="control-label col-sm-6") }}
<div class="col-sm-6">{{ form.value(class_="form-control")|safe }}
{%- if form.value.errors %}{% for error in form.value.errors %}
		<div class="alert alert-danger alert-dismissable" role='alert'>
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		{{ error }}
		</div>
{% endfor %}{% endif %}
</div></div>
{{ form.hidden_tag() }}
<div id="LogFormErr"></div>
</div>
<div class="modal-footer">
<button type="button" id="LogFormBtn" class="btn btn-success" data-id="{{view['id']}}">Log...</button>
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
</form>

todolist/templates/tasks/task_done.html
<span class="glyphicon glyphicon-check" aria-hidden="true" style="color:#009900"></span>

todolist/templates/tasks/tasks_give.html
{% extends 'base.html' %}

{% block container %}

<ul class="nav nav-tabs">
  <li role="presentation" {% if view.name=='User to Task' %}class='active'{%endif%}><a class="nav-link" href="{{ url_for('tasks.usertask') }}">User to Task</a></li>
  <li role="presentation" {% if view.name=='User to Equipment' %}class='active'{%endif%}><a class="nav-link" href="{{ url_for('tasks.userequipment') }}">User to Equipment</a></li>
</ul>
<p/>
<div class="container">
  <div class="form-group col-md-6">
  <label>{{ view.pickuser.usersfield.label }}</label>
  {{ view.pickuser.usersfield(class="form-control") }}
  </div>
  <div class="form-group col-md-6">
    <label>{{ view.pickuser.priority.label }}</label>
  {{ view.pickuser.priority(class="form-control") }}
  </div>
</div>
  
<div class="table-responsive" id='dtable'>
{{ view.table }}	
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
<script>
$(document).ready(function() {

  $('#usersfield').on('change', function(){
	var user=$(this).val();
	var urlbase="{{view.ajaxtable}}";
	var url = urlbase.concat('?user=',user);
	$('#dtable').html('<center><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></center>');
	$('#dtable').load(url, function() {
		$('#TaskTable').DataTable({
			paging: false
		});
	});
  });

  $('#dtable').on( 'click', ' tr', function(){
    var urlbase="{{view.ajaxtoggle}}";
	var td = $(this).find('#ToggleBtn')
	var lineid=td.data('myid')
	var userid=$('#usersfield').val()
	var prior=$('#priority').val()
	var url = urlbase.concat('?user=',userid).concat('&line=',lineid).concat('&pr=',prior);
	td.html('<span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>');
	td.load(url)
  });


    $('#TaskTable').DataTable({
		paging: false
	});
});
</script>
{% endblock %}

todolist/templates/tasks/tasks_giveajax.html
{{ data }}

todolist/templates/tasks/tasks_list.html
{% extends 'base.html' %}

{% block container %}
<!-- Modal -->
<div class="modal fade" id="TaskPopup" tabindex="-1" role="dialog" aria-labelledby="TaskEditLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                 <h4 class="modal-title" id="TaskEditLabel">Modal title</h4>
            </div>
            <div class="modal-body">...</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

  <h1>Tasks</h1>
  <div class="container">
  <h3>You can do something with your tasks.</h3>
  <ul>
	<li>You can multi-sort by shift-clicking the coloumns</li>
	<li>All tasks show Task priority while My Task show your priority for the task</li>
  </ul>

  {% if page=='Admin' %}{% if current_user.has_role('Admin') %}<a href="{{ url_for('tasks.edit') }}" class="btn btn-success" role="button">New Task</a>{%- endif %}{% else %}
  <a href="{{url_for("tasks.home",dd='dd', tsk='my' )}}" class="btn btn-primary" role="button">My Tasks to date</a>
	<a href="{{url_for("tasks.home",dd='all',tsk='my' )}}" class="btn btn-primary" role="button">My Tasks</a>
	&nbsp;
	<a href="{{url_for("tasks.home",dd='dd', tsk='all')}}" class="btn btn-info" role="button">All Tasks to date</a>
	<a href="{{url_for("tasks.home",dd='all',tsk='all')}}" class="btn btn-info" role="button">All Tasks</a>

  {%- endif %}
  </div>
<hr>
<div class="table-responsive">
{{ table }}
</div>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
<script>
$(document).ready(function() {
    $('#TaskTable').DataTable({
		paging: false,
		{% if table.order -%}
		 order: [[ {{table.order}}, "desc" ]]
		{% else -%}
		 order: [[ 0, "desc" ]]
		{%- endif %}
	});

// Fill modal with content from link href
$(".TaskDesc").click(function() {
	var taskid = $(this).data('id')
	var urlbase="{{url_for('tasks.taskpopup')}}";
	var url = urlbase.concat('?id=',taskid);
	$("#TaskPopup").find(".modal-title").text('* * * * *')
    $("#TaskPopup").find(".modal-body").text('Loading...')
	$("#TaskPopup").modal('show');
	$("#TaskPopup").find(".modal-content").load(url, function( response, status, xhr ) {
		if ( status == "error" ) {
			var msg = "Sorry but there was an error: ";
			$("#TaskPopup").find(".modal-body").html( 'Failed:' + xhr.status + " " + xhr.statusText );
			}
		});
});
//Done button pressed
$( ".TaskDone" ).click(function() {
	var mytd = $(this).parent()
	var taskid = $(this).data('id')
	//mytd.html('Failed')
	var urlbase="{{url_for('tasks.taskdone')}}";
	var url = urlbase.concat('?id=',taskid);
	$.ajax({
			url:url,
			type:'POST',
			dataType: 'text',
			success: function(data) {
				mytd.html(data)
			},
			error: function(xmlhttprequest, textstatus, message) {
					alert("An error has occurred making the request:\n" + message);
			}
	});
});
//Log button pressed
$( ".TaskLog" ).click(function() {
	var taskid = $(this).data('logid')
	var urlbase="{{url_for('tasks.tasklog')}}";
	var url = urlbase.concat('?id=',taskid);
	$("#TaskPopup").find(".modal-title").text('Log value')
	$("#TaskPopup").find(".modal-body").text('Loading...')
	$("#TaskPopup").modal('show');
	$("#TaskPopup").find(".modal-content").load(url, function( response, status, xhr ) {
		if ( status == "error" ) {
			var msg = "Sorry but there was an error: ";
			$("#TaskPopup").find(".modal-body").html( 'Failed:' + xhr.status + " " + xhr.statusText );
			}
		});
});
$("#TaskPopup").on( 'click', "#LogFormBtn", function() {
	var taskid = $(this).data('id')
	var urlbase="{{url_for('tasks.tasklog')}}";
	var url = urlbase.concat('?id=',taskid);
	$.ajax({
		type:"POST",
		url:url,
		data: $('#LogForm').serialize(),
		success: function(data,st,xhr) {
			if ( xhr.status == 201 ) {
				$('[data-logid='+taskid+']').parent().html(data);
				$("#TaskPopup").modal('hide');
			} else if ( xhr.status == 200 ){
				$("#TaskPopup").find(".modal-content").html(data);
				console.log(data);
			}
		},
		error: function(xhr, text, error) {
			$("#LogFormErr").html('Error: '+ error);
			console.log(xhr);
		}
	})
});

} );
</script>
{% endblock %}